
begin;

-- =========================================================
-- auth helpers for Discord OAuth + RLS
-- =========================================================
create or replace function public.current_discord_user_id()
returns text
language sql
stable
as $$
  select coalesce(
    auth.jwt() -> 'user_metadata' ->> 'provider_id',
    auth.jwt() -> 'user_metadata' ->> 'sub',
    auth.jwt() -> 'app_metadata' ->> 'provider_id'
  );
$$;

create or replace function public.is_guild_admin(check_guild_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.guild_admins ga
    where ga.guild_id = check_guild_id
      and ga.user_id = public.current_discord_user_id()
  );
$$;

-- =========================================================
-- core tables
-- =========================================================
create table if not exists public.bot_guilds (
  guild_id text primary key,
  name text default '',
  icon text,
  owner_id text,
  member_count integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.bot_guilds
  add column if not exists owner_id text,
  add column if not exists member_count integer not null default 0;

create table if not exists public.guild_admins (
  guild_id text not null,
  user_id text not null,
  role text not null default 'admin',
  created_at timestamptz not null default now(),
  primary key (guild_id, user_id)
);

create table if not exists public.guild_configs (
  guild_id text primary key,
  prefix text not null default '.',
  enabled_modules jsonb not null default '{}'::jsonb,
  disabled_commands jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  mod_roles jsonb not null default '[]'::jsonb,
  admin_roles jsonb not null default '[]'::jsonb
);

-- =========================================================
-- command system
-- =========================================================
create table if not exists public.commands_registry (
  command_name text primary key,
  category text not null default 'unknown',
  description text not null default '',
  is_active boolean not null default true,
  is_public boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.command_permissions (
  guild_id text not null,
  command_name text not null,
  enabled boolean not null default true,
  allowed_roles jsonb not null default '[]'::jsonb,
  denied_roles jsonb not null default '[]'::jsonb,
  allowed_channels jsonb not null default '[]'::jsonb,
  denied_channels jsonb not null default '[]'::jsonb,
  cooldown integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (guild_id, command_name)
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'command_permissions_command_name_fkey'
  ) then
    alter table public.command_permissions
      add constraint command_permissions_command_name_fkey
      foreign key (command_name)
      references public.commands_registry (command_name)
      on delete cascade;
  end if;
end $$;

create table if not exists public.custom_commands (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  name text,
  command_name text,
  response text not null default '',
  enabled boolean not null default true,
  embed_enabled boolean not null default false,
  allowed_roles jsonb not null default '[]'::jsonb,
  denied_roles jsonb not null default '[]'::jsonb,
  allowed_channels jsonb not null default '[]'::jsonb,
  denied_channels jsonb not null default '[]'::jsonb,
  cooldown integer not null default 0,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.custom_commands
  add column if not exists command_name text,
  add column if not exists enabled boolean not null default true,
  add column if not exists embed_enabled boolean not null default false,
  add column if not exists allowed_roles jsonb not null default '[]'::jsonb,
  add column if not exists denied_roles jsonb not null default '[]'::jsonb,
  add column if not exists allowed_channels jsonb not null default '[]'::jsonb,
  add column if not exists denied_channels jsonb not null default '[]'::jsonb,
  add column if not exists cooldown integer not null default 0;

update public.custom_commands
set command_name = name
where command_name is null and name is not null;

create unique index if not exists custom_commands_guild_id_command_name_uq
on public.custom_commands (guild_id, command_name);

-- =========================================================
-- rules
-- =========================================================
create table if not exists public.guild_rules (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  rule_order integer not null default 0,
  title text not null default '',
  content text not null default '',
  enabled boolean not null default true,
  rules_md text,
  updated_at timestamptz not null default now()
);

alter table public.guild_rules
  add column if not exists id bigint generated by default as identity,
  add column if not exists rule_order integer not null default 0,
  add column if not exists title text not null default '',
  add column if not exists content text not null default '',
  add column if not exists enabled boolean not null default true;

create index if not exists guild_rules_guild_id_order_idx
on public.guild_rules (guild_id, rule_order);

-- =========================================================
-- logs: separate settings and entries
-- =========================================================
create table if not exists public.guild_log_settings (
  guild_id text not null,
  log_type text not null,
  channel_id text,
  enabled boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (guild_id, log_type)
);

create table if not exists public.guild_logs (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  type text,
  log_type text,
  user_id text,
  target_id text,
  moderator_id text,
  message text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.guild_logs
  add column if not exists log_type text;

update public.guild_logs
set log_type = type
where log_type is null and type is not null;

create index if not exists guild_logs_guild_id_created_idx
on public.guild_logs (guild_id, created_at desc);

-- =========================================================
-- moderation
-- =========================================================
create table if not exists public.guild_cases (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  target_id text,
  moderator_id text,
  type text not null,
  reason text,
  active boolean not null default true,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  revoked_at timestamptz
);

create index if not exists guild_cases_guild_id_created_idx
on public.guild_cases (guild_id, created_at desc);

create table if not exists public.guild_mod_history (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.temp_bans (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  user_id text not null,
  moderator_id text,
  reason text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb
);

create table if not exists public.temp_roles (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  user_id text not null,
  role_id text not null,
  moderator_id text,
  reason text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb
);

-- =========================================================
-- tickets
-- =========================================================
create table if not exists public.ticket_configs (
  guild_id text primary key,
  enabled boolean not null default false,
  category_id text,
  channel_id text,
  log_channel_id text,
  support_roles jsonb not null default '[]'::jsonb,
  ticket_name_template text not null default 'ticket-{user}',
  max_open_per_user integer not null default 1,
  panels jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.ticket_configs
  add column if not exists max_open_per_user integer not null default 1,
  add column if not exists panels jsonb not null default '[]'::jsonb;

create table if not exists public.ticket_panels (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  panel_name text not null default 'New Panel',
  panel_channel_id text,
  panel_message_id text,
  panel_type text not null default 'default',
  description text not null default '',
  button_label text not null default 'Open Ticket',
  button_style text not null default 'primary',
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create index if not exists ticket_panels_guild_id_updated_idx
on public.ticket_panels (guild_id, updated_at desc);

create table if not exists public.tickets (
  ticket_id text primary key,
  guild_id text not null,
  channel_id text,
  owner_id text,
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  status text not null default 'open',
  claimed_by text,
  panel_message_id text,
  panel_channel_id text,
  meta jsonb not null default '{}'::jsonb
);

-- =========================================================
-- voicemaster
-- =========================================================
create table if not exists public.voicemaster_configs (
  guild_id text primary key,
  config jsonb not null default '{}'::jsonb,
  enabled boolean not null default false,
  creator_channel_id text,
  category_id text,
  log_channel_id text,
  room_name_template text not null default '{username}''s room',
  default_user_limit integer not null default 0,
  allow_rename boolean not null default true,
  allow_lock boolean not null default true,
  allow_hide boolean not null default true,
  allow_transfer boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.voicemaster_configs
  add column if not exists enabled boolean not null default false,
  add column if not exists creator_channel_id text,
  add column if not exists category_id text,
  add column if not exists log_channel_id text,
  add column if not exists room_name_template text not null default '{username}''s room',
  add column if not exists default_user_limit integer not null default 0,
  add column if not exists allow_rename boolean not null default true,
  add column if not exists allow_lock boolean not null default true,
  add column if not exists allow_hide boolean not null default true,
  add column if not exists allow_transfer boolean not null default true;

create table if not exists public.voicemaster_rooms (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  channel_id text not null,
  owner_id text,
  member_count integer not null default 0,
  is_locked boolean not null default false,
  is_hidden boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists voicemaster_rooms_channel_id_uq
on public.voicemaster_rooms (channel_id);

-- =========================================================
-- server customizations
-- =========================================================
create table if not exists public.server_customizations (
  guild_id text primary key,
  data jsonb not null default '{}'::jsonb,
  embed_color text not null default '#8b5cf6',
  footer_text text not null default '',
  footer_icon_url text not null default '',
  webhook_name text not null default '',
  webhook_avatar_url text not null default '',
  banner_url text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.server_customizations
  add column if not exists embed_color text not null default '#8b5cf6',
  add column if not exists footer_text text not null default '',
  add column if not exists footer_icon_url text not null default '',
  add column if not exists webhook_name text not null default '',
  add column if not exists webhook_avatar_url text not null default '',
  add column if not exists banner_url text not null default '';

-- =========================================================
-- optional / keep
-- =========================================================
create table if not exists public.bot_meta (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.bot_analytics (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.bot_storage (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

commit;

-- =========================================================
-- RLS
-- =========================================================
alter table public.guild_admins enable row level security;
alter table public.bot_guilds enable row level security;
alter table public.guild_configs enable row level security;
alter table public.commands_registry enable row level security;
alter table public.command_permissions enable row level security;
alter table public.custom_commands enable row level security;
alter table public.guild_rules enable row level security;
alter table public.guild_log_settings enable row level security;
alter table public.guild_logs enable row level security;
alter table public.guild_cases enable row level security;
alter table public.guild_mod_history enable row level security;
alter table public.temp_bans enable row level security;
alter table public.temp_roles enable row level security;
alter table public.ticket_configs enable row level security;
alter table public.ticket_panels enable row level security;
alter table public.tickets enable row level security;
alter table public.voicemaster_configs enable row level security;
alter table public.voicemaster_rooms enable row level security;
alter table public.server_customizations enable row level security;
alter table public.bot_meta enable row level security;
alter table public.bot_analytics enable row level security;
alter table public.bot_storage enable row level security;

drop policy if exists guild_admins_self_read on public.guild_admins;
create policy guild_admins_self_read on public.guild_admins
for select
to authenticated
using (user_id = public.current_discord_user_id());

drop policy if exists guild_admins_self_write on public.guild_admins;
create policy guild_admins_self_write on public.guild_admins
for all
to authenticated
using (user_id = public.current_discord_user_id())
with check (user_id = public.current_discord_user_id());

drop policy if exists bot_guilds_admin_read on public.bot_guilds;
create policy bot_guilds_admin_read on public.bot_guilds
for select
to authenticated
using (public.is_guild_admin(guild_id));

drop policy if exists bot_guilds_admin_write on public.bot_guilds;
create policy bot_guilds_admin_write on public.bot_guilds
for all
to authenticated
using (public.is_guild_admin(guild_id))
with check (public.is_guild_admin(guild_id));

drop policy if exists commands_registry_read on public.commands_registry;
create policy commands_registry_read on public.commands_registry
for select
to authenticated
using (true);

drop policy if exists commands_registry_write on public.commands_registry;
create policy commands_registry_write on public.commands_registry
for all
to authenticated
using (false)
with check (false);

-- guild-scoped tables
do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'guild_configs',
    'command_permissions',
    'custom_commands',
    'guild_rules',
    'guild_log_settings',
    'guild_logs',
    'guild_cases',
    'guild_mod_history',
    'temp_bans',
    'temp_roles',
    'ticket_configs',
    'ticket_panels',
    'tickets',
    'voicemaster_configs',
    'voicemaster_rooms',
    'server_customizations'
  ]
  loop
    execute format('drop policy if exists %I_admin_select on public.%I', tbl, tbl);
    execute format('create policy %I_admin_select on public.%I for select to authenticated using (public.is_guild_admin(guild_id))', tbl, tbl);
    execute format('drop policy if exists %I_admin_write on public.%I', tbl, tbl);
    execute format('create policy %I_admin_write on public.%I for all to authenticated using (public.is_guild_admin(guild_id)) with check (public.is_guild_admin(guild_id))', tbl, tbl);
  end loop;
end $$;

-- block client access to system tables
drop policy if exists bot_meta_none on public.bot_meta;
create policy bot_meta_none on public.bot_meta for all to authenticated using (false) with check (false);
drop policy if exists bot_analytics_none on public.bot_analytics;
create policy bot_analytics_none on public.bot_analytics for all to authenticated using (false) with check (false);
drop policy if exists bot_storage_none on public.bot_storage;
create policy bot_storage_none on public.bot_storage for all to authenticated using (false) with check (false);
