var root=document.getElementById('rulesView');var L=window.Lunaria;var supabase=L.client;
async function loadRows(guildId){var r=await supabase.from('guild_rules').select('*').eq('guild_id',guildId).order('rule_order');if(r.error)throw new Error('guild_rules: '+r.error.message);return r.data||[];}
async function saveRow(row){var r=await supabase.from('guild_rules').upsert(row);if(r.error)throw new Error('guild_rules save: '+r.error.message);}
async function deleteRow(id){var r=await supabase.from('guild_rules').delete().eq('id',id);if(r.error)throw new Error('guild_rules delete: '+r.error.message);}
function editor(row){row=row||{rule_order:0,title:'',content:'',enabled:true};return '<div class="grid grid-2"><div class="card"><div class="field"><label for="rule_order">Order</label><input id="rule_order" type="number" value="'+L.esc(row.rule_order||0)+'"></div><div class="field"><label for="title">Title</label><input id="title" type="text" value="'+L.esc(row.title||'')+'"></div></div><div class="card"><div class="field"><label for="content">Content</label><textarea id="content">'+L.esc(row.content||'')+'</textarea></div><div class="field"><label><input id="enabled" type="checkbox" '+(row.enabled!==false?'checked':'')+'> Enabled</label></div></div></div><div class="card" style="margin-top:18px"><div class="actions"><button id="saveBtn">Save</button><button class="secondary" id="cancelBtn">Cancel</button></div><p id="status" class="muted" style="margin-top:14px"></p></div>';}
async function start(){try{var guildId=L.queryParam('guild');if(!guildId)throw new Error('Не передан guild id.');var access=await L.requireGuildAccess(guildId);renderList(access,await loadRows(guildId));}catch(err){L.showLayout(root,'rules','Ошибка','Rules failed to load.','<div class="card"><p>'+L.esc(L.errorText(err))+'</p></div>');}}
function renderList(access,rows){var html='<div class="card"><div class="split"><div><h2>Rules</h2><p class="muted">Manage displayed rules for this server.</p></div><div class="actions"><button id="newBtn">New rule</button></div></div><hr><div class="stack">'+(rows.length?rows.map(function(row){return '<div class="list-item"><div class="server-info"><h3>#'+L.esc(row.rule_order)+' — '+L.esc(row.title||'Untitled')+'</h3><p>'+L.esc(row.content||'')+'</p><div>'+(row.enabled!==false?'<span class="chip">Enabled</span>':'<span class="chip muted">Disabled</span>')+'</div></div><div class="actions"><button class="secondary" data-edit="'+L.esc(row.id)+'">Edit</button><button class="danger" data-del="'+L.esc(row.id)+'">Delete</button></div></div>';}).join(''):'<div class="empty">No rules yet.</div>')+'</div></div>';L.showLayout(root,'rules',(access.guild.name||'Server')+' Rules','Rule management.',html);document.getElementById('newBtn').addEventListener('click',function(){openEditor(access,rows,null);});Array.prototype.forEach.call(document.querySelectorAll('[data-edit]'),function(btn){btn.addEventListener('click',function(){openEditor(access,rows,rows.find(function(x){return String(x.id)===btn.getAttribute('data-edit');}));});});Array.prototype.forEach.call(document.querySelectorAll('[data-del]'),function(btn){btn.addEventListener('click',async function(){if(!confirm('Delete this rule?'))return;try{await deleteRow(btn.getAttribute('data-del'));renderList(access,await loadRows(access.guild.guild_id));}catch(err){alert(L.errorText(err));}});});}
function openEditor(access,rows,row){L.showLayout(root,'rules',row?'Edit Rule':'New Rule','Rule editor.',editor(row));document.getElementById('cancelBtn').addEventListener('click',function(){renderList(access,rows);});document.getElementById('saveBtn').addEventListener('click',async function(){var status=document.getElementById('status');try{status.textContent='Saving...';await saveRow({id:row&&row.id?row.id:undefined,guild_id:access.guild.guild_id,rule_order:Math.max(0,parseInt(document.getElementById('rule_order').value||'0',10)||0),title:document.getElementById('title').value||'',content:document.getElementById('content').value||'',enabled:document.getElementById('enabled').checked,updated_at:new Date().toISOString()});renderList(access,await loadRows(access.guild.guild_id));}catch(err){status.textContent='ERROR: '+L.errorText(err);}});}
start();
